permalink: '/:title/'
color_scheme: light
accent_color: pink
header:
  title: Exto
  has_nav: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
title: Stackbit Exto Theme
baseurl: /
footer:
  content: '&copy; Stackbit-Exto. All rights reserved.'
  links:
    - text: Made with Stackbit
      url: 'https://www.stackbit.com'
      new_window: true
    - new_window: true
      text: 'Aviso legal. '
      url: /legal/
    - new_window: true
      text: Protección de datos
      url: /datos/
  has_social: false
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
